### ISSUE TITLE
Tried out Plus1 firmware

### ISSUE THREAD

**Issue by lbschenkel** [phiten/mgos32-to-tasmota32#1]
I'm not sure if you're looking for reports, but I tried out doing an OTA with a Shelly Plus 1. This is what happened:
1. The OTA itself worked
2. Device rebooted and opened a hotspot
3. When connected to the hotspot, I am able to enter my WLAN credentials and save
4. Device connects to WLAN, I can ping it and open the web interface
5. **However**: after a few seconds the device is no longer in the WLAN, and only accessible via hotspot

So I'm now stuck in this state. I could also not see a button to manually upload new firmware?

**Comment by phiten** [comment]
Hi,

It seems like the links are not updating with the latest files in this repo. So you flashed an older version of the OTA files.

Please try to do the following:

1. Try to add it back to your wifi.
2. Try to start an OTA with this link from tasmota. http://ota.tasmota.com/tasmota32/tasmota32solo1.bin

**Comment by lbschenkel** [comment]
Thanks for the quick reply!

1. How can I start a new OTA? As I mentioned, the web interface only has the buttons to update/reset the config, no option to upload a new firmware.
2. The device won't stay in the WLAN for more than a few seconds (~5 seconds), I guess it's resetting itself. So I need to OTA by connecting to the device's AP instead (which I guess is the same?)

**Comment by phiten** [comment]
Please have a look at the tasmota docs: https://tasmota.github.io/docs/Upgrading/#upgrade-using-webui

**Comment by lbschenkel** [comment]
> Please have a look at the tasmota docs: https://tasmota.github.io/docs/Upgrading/#upgrade-using-webui

I understand this, I have done it before (for other devices), but what I'm trying to say is that the firmware that I used to OTA (the one linked to in the README) **does not** have any of this UI available. The only buttons that appear in the bottom are to reset config and reboot device. That's it.

**Comment by lbschenkel** [comment]
Let me show what the UI has (removed my WLAN names):
![Screenshot_20230123-090242~2](https://user-images.githubusercontent.com/1428661/213991647-7faa6730-bc8b-4edb-ba7a-942a7299aa44.png)

I guess I'm just out of luck and need to serial flash. That's fine, I was going to do that anyway since it was the only way available, but then I stumbled upon this and wanted to give it a shot.

I suggest that you take down/change/update the links or put a stronger warning in the README to caution other potential users that the firmware for the Shelly Plus 1 is not really working and they should not attempt to OTA.

**Comment by phiten** [comment]
Do you have another Shelly Plus 1? If yes you could do a full FW dump and flash the dump to your other Plus 1. The link is now updated. So you could try the OTA again. You can confirm this by downloading the [ZIP](http://ota.tasmota.com/tasmota32/shelly/mgos32-to-tasmota32-Plus1.zip) to your PC and confirm that either through the name of the file system image (fs-4MB-tasmota.img) or the build date in the manifest.json.

This would help a lot to get more devices tested.

**Comment by lbschenkel** [comment]
Unfortunately I don't; this was my first "plus" device which I bought for testing before committing into buying more. Once I realized I could not do OTA (before I found this repo) I ordered a serial programmer online, but then I found this and decided to try it out.

What I can do is to recover it with the serial cable once I have it, flash Tasmota, flash stock, and then try the OTA procedure again and report it here.

**Comment by phiten** [comment]
Ok. As we don't whats the issue I would close this issue for now. I only have a Plus 1PM which works fine. Hopefully we have the 8MB devices supported in the next few days so I can test the Pro 4PM. I'm going to order a Plus 1 to see if I can reproduce the issue.

**Comment by phiten** [comment]
@lbschenkel So I simulated a Plus 1 on my dev board and the upgrade went perfectly fine. 
There are two options that may have happened:
1. your Shelly Plus 1 is defect and some ghost input led to resets.
2. The old image bricked the device in the update process.

I have two Plus 1 coming in on Wednesday and I will check the conversion with the actual device. I assume everything will be working as expected.

**Comment by phiten** [comment]
@lbschenkel So I tested with two different Shelly Plus1 today and everything works fine. The only thing I discovered is that my Shelly Plus 1 came with the version 0.9.2-beta2 running from app_1 partition. When updated to 0.12.0 Shelly runs from app_0 partition. The OTA conversion writes to app_0 from which Shelly is running on. That means on the next boot Shelly OS (booting app_1) is back. But the OTA process can then simply be done again which instantly reboots the Shelly device as the app_0 partition has the same version number as the update. The result is a tasmota hotspot as described.

I added the following sentence to the README for further clarification:

`If Shelly OS (Mongoose OS) boots back up after the OTA update, please update (using the OTA link from this repo) again.`

**Comment by lbschenkel** [comment]
To clarify; this was *after* you updated the OTA files, so it's not the same version I attempted to use, correct?

**Comment by phiten** [comment]
Yes thats correct. The OTA update your Shelly downloaded should have worked, but used some older files in the ZIP which may have caused the update to fail.

**Comment by lbschenkel** [comment]
I did not know that Shelly Plus had two partitions. Do you know how can I trigger the bootloader to use the other one? I am yet waiting for my serial cable to arrive; but in the meantime I could wire it again and see if I can force a boot into the other partition, which hopefully still has Mongoose.

**Comment by phiten** [comment]
There is no way without a serial cable or a running tasmota incl. Berry console sadly.

You could wire it anyway to see if it fixed itself somehow.
