### ISSUE TITLE
Way back to original firmware

### ISSUE THREAD

**Issue by Bascht74** [phiten/mgos32-to-tasmota32#15]
Hi there, 

is there a way to go back to the original firmware?
Thx for any hints...

**Comment by phiten** [comment]
Technically you should be able to upload the .bin file from the Shelly update zip file to tasmota and get back to mongoose os. I never tested it tho.

**Comment by Bascht74** [comment]
I got a solution: 
I downloaded mos tool (which is from mongoose os used by Shelly Gen2 for OTA):
[https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md 61](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md)

downloaded the stock firmware here:
http://rojer.me/files/shelly/stock/

Flashed it via:
`mos flash --esp-baud-rate 460800 Plus1PM.zip`
