### ISSUE TITLE
Use factory calibration not working

### ISSUE THREAD

**Issue by to-scho** [phiten/mgos32-to-tasmota32#16]
I flashed my Shelly Plus Plug S with Tasmota like a charm, thx for that.

I then tried "Optional: Use factory calibration data" but have the following issues:
-There are no shelly.bin and aux.bin (also no Shelly_data.be nor Shelly_data.tapp)
-import Shelly_data gives error: BRY: Exception> 'import_error' -module 'Shelly_data' not found
 stack traceback: <unknown source>: in function 'main'

Is the doc referring to some old Tasmota version and use of factory cal is not possible any more or do I miss something here?

**Comment by phiten** [comment]
I only tested this method with a Plus 1PM and a Pro 4PM. But there is no way to use it correctly yet in tasmota as far as I know.
