### ISSUE TITLE
PlusHT working

### ISSUE THREAD

**Issue by BigNerd95** [phiten/mgos32-to-tasmota32#19]
Just flashed on a PlusHT and it works, i can connect to tasmota AP and see the configs.
What should i do to write what i want on the screen?

**Comment by phiten** [comment]
I'm just offering the OTA conversion. For configuration questions please refer to the tasmota docs or ask in the tasmota community.

**Comment by BigNerd95** [comment]
Ok thank you! I think you can update the readme with "tested"
