### ISSUE TITLE
Device report: Shelly Plus 1PM and Shelly Plus 2PM

### ISSUE THREAD

**Issue by controlcde** [phiten/mgos32-to-tasmota32#2]
Because I can´t open an issue at [https://github.com/tasmota/mgos32-to-tasmota32](https://github.com/tasmota/mgos32-to-tasmota32) (There is no issues tab) I´ll do it here. I´ve updated two devices: Shelly Plus 1PM and Shelly Plus 2PM. The 2PM works but it seams that the 1PM is broken after I uploaded the firmware - I can´t see the device in my wifi nor it will create an own ap. I don´t have a serial2usb cable to try flashing it so I can´t provide further informations.

**Comment by phiten** [comment]
Can you please try this recovery method and see if the device is opening it's AP after that?

https://tasmota.github.io/docs/Device-Recovery/#fast-power-cycle-device-recovery

**Comment by controlcde** [comment]
sadly it doesn´t work :(

**Comment by phiten** [comment]
It's weird that you have the problems with the Plus 1PM because that's actually the device I tested on all the time while developing.

As I'm still unsure if tasmota was actually installed, do you hear the Relay clicking when you press the button on the Plus 1PM when it is connected to power? If yes that means that it's still the original Shelly firmware and you would need to reset through the Shelly procedure described here under `User Interface > Inputs` https://kb.shelly.cloud/knowledge-base/shelly-plus-1pm

**Comment by controlcde** [comment]
nope - no click and no led blinking :(

It seams so that I have to buy a flashing cable. Any advice for an adapter cable?

**Comment by phiten** [comment]
See the Infos here: https://tasmota.github.io/docs/Getting-Started/#needed-hardware

If you have an ESP8266 or ESP32 dev board with a USB-Serial chip build in you can use that one.

The pin header of the Shelly devices is quite small normal dupont cables won't fit. You can use sewing pins poked through the plug of the dupont cable to adapt to Shelly pin thickness.

If you want to flash multiple Shelly's this is probably the best investment: https://www.tindie.com/products/voltlog/voltlink-cp2102n-usb-serial-adapter-programmer/ just make sure to order the Shelly programming adapter with it.

**Comment by phiten** [comment]
Which Shelly version did you have installed when you started the OTA update to tasmota?

**Comment by controlcde** [comment]
> Which Shelly version did you have installed when you started the OTA update to tasmota?

0.12.0 - latest Stable.

**Comment by phiten** [comment]
Okay currently I can't reproduce that issue. Will do more testing.
