### ISSUE TITLE
Add support for shelly plus 1 mini

### ISSUE THREAD

**Issue by Schrankus** [phiten/mgos32-to-tasmota32#22]
It would be awesome to add support for shelly plus 1 mini.

Link to knowledge base: https://kb.shelly.cloud/knowledge-base/shelly-plus-1-mini

**Comment by phiten** [comment]
I will have a look at all new Plus and Pro devices next week.

**Comment by Jason2866** [comment]
@Schrankus Can you provide a dump of the whole firmware?
Shelly changed the partition scheme for the C3 builds. Without a full dump not possible to add support.

**Comment by Jason2866** [comment]
Managed to rebuild a full factory image which boots successfully on a C3 devboard.
Working on the support to do OTA Converting for this devices

**Comment by Jason2866** [comment]
Progress. Successfully OTA converted a `Plus1PMMini`. Still not ready for release, since converting to the needed safeboot scheme is not (yet) working. The Partition Wizard needs changes. Same issue as in #23

**Comment by Jason2866** [comment]
@Schrankus You can try https://github.com/tasmota/mgos32-to-tasmota32/releases/download/C3_Shelly/mgos32-to-tasmota32-Plus1PMMini.zip
Download and drag and drop in the Shelly firmware upload area.
After the convert the Tasmota AP opens. Configure your WiFi.
When connected go in FS and delete the big HTML.gzip file.
Now go in Autoconfig and choose the device. 
MANDANTORY After the device is back and configured upload PartitionWizard in the FS and start it. After it has finished (be patient a few minutes), device is back on latest Tasmota release Version. For a working device you have to install latest development version.

Every step is needed! Without it can end in a serial reflash.

**Comment by Schrankus** [comment]
Thank you very much. I will try in the next 2 days :)

**Comment by Jason2866** [comment]
@Schrankus Final version online. Simplified :-)
Download and drag and drop in the Shelly firmware upload area: https://github.com/tasmota/mgos32-to-tasmota32/releases/download/C3_Shelly/mgos32-to-tasmota32-Plus1PMMini.zip
After the convert the Tasmota AP opens. Configure your WiFi.
When connected go in Autoconfig and choose the device.
MANDANTORY After the device is back start the now installed PartitionWizard. After it has finished (be patient a few minutes), device is back on latest Tasmota release Version. For a working device you have to install latest development version.

**Comment by Schrankus** [comment]
I am quite confused. I don't know if it's my fault. But currently my two shellies won't accept the firmware upload at all. Neither via drag'n'drop nor via link nor via api. They just seem to reload the button but nothing happens. Via api I am getting a "Trying to update from ..." response... Not sure if that is a known issue or if I am too stupid.

But seems to be a shelly firmware issue...

**Comment by Jason2866** [comment]
@Schrankus Ahh, SORRY !! You have a Shelly Plus1Mini NOT the Shelly Plus1PMMini. Gave you the wrong link.
Thats the one https://github.com/tasmota/mgos32-to-tasmota32/releases/download/v13.1/mgos32-to-tasmota32-Plus1Mini.zip

**Comment by Schrankus** [comment]
Okay. I now got the tasmota firmware onto my two shellies. But after I selected the auto config and they requested to restart it got back to the shelly firmware... After that I am now unable to install the tasmota firmware again. Even after factory reset. 

So I am unable to get to your explanations mandatory part :(

**Comment by Jason2866** [comment]
Weird. Tested on mine. So Shelly has more restrictions which i did not encountered in my tests.
Tbh currently i have no idea how to solve since i cant reproduce :-(

**Comment by Jason2866** [comment]
Got an idea what might happen, have to check this assumption. If the theory is correct it needs some more extra code to workaround this.

**Comment by Jason2866** [comment]
Theory confirmed. Removed all convert packages. Can hit every device which has the new Shelly firmware.
Working on a solution

**Comment by Jason2866** [comment]
Solved. Follow the description in repo https://github.com/tasmota/mgos32-to-tasmota32
BUT Shellys stuck in Shelly firmware (issue caused from the not complete working first convert version) can only converted to Tasmota by serial flashing. Sorry!

**Comment by nathanmarlor** [comment]
In case anyone else ends up with a bricked device (user error :)) here's the serial pin out from my Shelly 1 PM Plus Mini. Successfully recovered by flashing ESPHome directly. 

![PXL_20230927_114038664](https://github.com/phiten/mgos32-to-tasmota32/assets/3436911/cbc8739b-7fc7-4dee-a6c4-3f6d60eaec73)

**Comment by Jason2866** [comment]
Shelly minis are supported now. Needed Infos and packages are here https://github.com/tasmota/mgos32-to-tasmota32
