### ISSUE TITLE
Error: "boot: ota data partition invalid, falling back to factory"

### ISSUE THREAD

**Issue by RavenSystem** [phiten/mgos32-to-tasmota32#23]
There is an issue with some Shellys that is causing corruption with ota partition, avoiding to select a boot partition different from ota_0 or safeboot.

Flashing from Mongoose Shelly firmware to Tasmota works fine, but flashing other Tasmota firmwares from initial Tasmota causes this error:

```
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length   F
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000 0
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000 1
I (84) boot:  2 app_0            OTA app          00 10 00010000 00180000 1
I (91) boot:  3 fs_0             FS               01 82 00190000 00070000 1
I (99) boot:  4 app_1            OTA app          00 11 00200000 00180000 1
I (106) boot:  5 fs_1             FS               01 82 00380000 00070000 1
I (114) boot:  6 aux              unknown          55 00 003f0000 0000c000 0
I (122) boot:  7 shelly           Unknown data     01 88 003fc000 00004000 1
I (130) boot: End of partition table
I (134) boot: OTA data 0: seq 0x00000001, st 0x11, CRC 0x4743989a, valid? 0
I (142) boot: OTA data 1: seq 0xffffffff, st 0xffffffff, CRC 0xffffffff, valid? 0
E (150) boot: ota data partition invalid and no factory, will try all partitions
```

```
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length   F
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000 0
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000 1
I (84) boot:  2 safeboot         factory app      00 00 00010000 000d0000 1
I (91) boot:  3 app0             OTA app          00 10 000e0000 002a0000 1
I (99) boot:  4 fs_1             FS               01 82 00380000 00070000 1
I (106) boot: End of partition table
I (111) boot: OTA data 0: seq 0x00000001, st 0xffffffff, CRC 0x4743989a, valid? 0
I (119) boot: OTA data 1: seq 0x00000001, st 0xffffffff, CRC 0x4743989a, valid? 0
E (127) boot: ota data partition invalid, falling back to factory
```

Here is a full flash backup of original stock firmware from a Shelly Plus 1PM device with the issue, done before first boot:
[ShellyPlus1PM_b48a0a1b8d0c.bin.zip](https://github.com/phiten/mgos32-to-tasmota32/files/12566111/ShellyPlus1PM_b48a0a1b8d0c.bin.zip)

Other Shelly Plus devices, like some 2PM, have this issue too.

**Comment by Jason2866** [comment]
Use Partition Wizard to change the FS size to 320k. This will update the partition scheme to be compatible with standard Tasmota builds

**Comment by RavenSystem** [comment]
And how is it possible? From Console? Because device is stuck at SAFEBOOT firmware because ota data partition is invalid, and it is unable to boot ota_0 partition.

**Comment by Jason2866** [comment]
Ahh, okay. Thought you are in stuck in Tasmota firmware. The partition resize step is mandatory. You can't flash a newer Tasmota version since the builds above v12.5 are too big to fit in the OTA slot. So do an OTA upgrade to v12.5 and do then the Partition resize.
You can do the upgrade via OTA or by file. Use ONLY the tasmota32-solo1!!

**Comment by RavenSystem** [comment]
I tried this, but device is unable to boot ota_0 partition. Safeboot flashes firmware, but it boots again at safeboot partition: `boot: ota data partition invalid, falling back to factory`.

After first installation of Tasmota, I run FS Wizard and changed partitions to safeboot layout. You can see logs and partitions at first post.

**Comment by RavenSystem** [comment]
The issue can be caused because Shelly is enabling secure boot for some new devices, and signature validation fails when Tasmota is installed, causing error on ota data:

```
I (134) boot: OTA data 0: seq 0x00000001, st 0x11, CRC 0x4743989a, valid? 0
I (142) boot: OTA data 1: seq 0xffffffff, st 0xffffffff, CRC 0xffffffff, valid? 0
E (150) boot: ota data partition invalid and no factory, will try all partitions
```

**Comment by Jason2866** [comment]
Ohh, this cpuld be the end of OTA conversion. Do you have a full orig. dump of such a new firmware? Will have a look in the one you provided already to see if this is here the problem already.
The error you see, could be a changed Shelly partition scheme, where our modified version is not compatible.
Since the bootloader and the firmware is replaced successfully, secure boot should not be active. And normally when secure boot is activated, dumping of flash is not possible.
-> efuse burnt

**Comment by RavenSystem** [comment]
Sure! I attached it at the first post. It is in a "virgin" state, done before first boot.

**Comment by RavenSystem** [comment]
This log is taken immediately after first installation of Tasmota via OTA, with original partition layout from Shelly, before run Partition Wizard. You can see error about ota data:

```
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length   F
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000 0
I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000 1
I (84) boot:  2 app_0            OTA app          00 10 00010000 00180000 1
I (91) boot:  3 fs_0             FS               01 82 00190000 00070000 1
I (99) boot:  4 app_1            OTA app          00 11 00200000 00180000 1
I (106) boot:  5 fs_1             FS               01 82 00380000 00070000 1
I (114) boot:  6 aux              unknown          55 00 003f0000 0000c000 0
I (122) boot:  7 shelly           Unknown data     01 88 003fc000 00004000 1
I (130) boot: End of partition table
I (134) boot: OTA data 0: seq 0x00000001, st 0x11, CRC 0x4743989a, valid? 0
I (142) boot: OTA data 1: seq 0xffffffff, st 0xffffffff, CRC 0xffffffff, valid? 0
E (150) boot: ota data partition invalid and no factory, will try all partitions
```

**Comment by RavenSystem** [comment]
About bootloader is replaced successfully, I am not sure. Secureboot should avoid this.

But I repeat, this issue is very new. And it only happens with a few devices, newest devices.

**Comment by Jason2866** [comment]
> This log is taken immediately before first installation of Tasmota via OTA, with original partition layout from Shelly, before run Partition Wizard. You can see error about ota data:
> 
> ```
> I (57) boot: Partition Table:
> I (61) boot: ## Label            Usage          Type ST Offset   Length   F
> I (68) boot:  0 nvs              WiFi data        01 02 00009000 00004000 0
> I (76) boot:  1 otadata          OTA data         01 00 0000d000 00002000 1
> I (84) boot:  2 app_0            OTA app          00 10 00010000 00180000 1
> I (91) boot:  3 fs_0             FS               01 82 00190000 00070000 1
> I (99) boot:  4 app_1            OTA app          00 11 00200000 00180000 1
> I (106) boot:  5 fs_1             FS               01 82 00380000 00070000 1
> I (114) boot:  6 aux              unknown          55 00 003f0000 0000c000 0
> I (122) boot:  7 shelly           Unknown data     01 88 003fc000 00004000 1
> I (130) boot: End of partition table
> I (134) boot: OTA data 0: seq 0x00000001, st 0x11, CRC 0x4743989a, valid? 0
> I (142) boot: OTA data 1: seq 0xffffffff, st 0xffffffff, CRC 0xffffffff, valid? 0
> E (150) boot: ota data partition invalid and no factory, will try all partitions
> ```

So the message is with the orig. firmware booting?

**Comment by RavenSystem** [comment]
Sorry, after, not before. I edited post.

**Comment by Jason2866** [comment]
This sort of error is typical when the used partition scheme (which is changed by the OTA convert) does not fit correctly. So most probably Shelly changed here "something".
To fix this issue i need a full dump of the orig. Shelly firmware.

**Comment by RavenSystem** [comment]
> This sort of error is typical when the used partition scheme (which is changed by the OTA convert) does not fit correctly. So most probably Shelly changed here "something".
> To fix this issue i need a full dump of the orig. Shelly firmware.

I attached a full dump of original Shelly firmware at first post.

**Comment by Jason2866** [comment]
@RavenSystem Can reproduce the issue. We are working on this

**Comment by RavenSystem** [comment]
Great! Many thanks.

**Comment by Jason2866** [comment]
Shelly has indeed changed to more strict OTA updating. 
Problem identified. New version coming soon. Needs some more trickery ;-)
BUT no way to recover devices which are stuck in safeboot without serial reflash.
Reason is the bootloader which checks for signed (Shelly) firmwares. None is found so it reverts to the version which is at address `0x10000`.
The new version is replacing the secured bootloader (via a Berry script running from the initial flashed Tasmota version) with a "normal" bootloader.

**Comment by Jason2866** [comment]
@RavenSystem final version online. OTA as described. After that go in Tasmota "Auto-Configuration" and select the device. After restart the "free" bootloader is flashed and PartitionWizard is installed. Start PartitionWizard, wait. Done!

**Comment by RavenSystem** [comment]
Great! I will reflash device by wire with original firmware to test OTA. I will report.

**Comment by Jason2866** [comment]
Will need a bit of time to add the other Shelly ESP32 devices

**Comment by RavenSystem** [comment]
Is Plus 1PM firmware ready?

**Comment by Jason2866** [comment]
yes

**Comment by RavenSystem** [comment]
I tested, but issue persists. Firmware is not able to select proper boot partition.

**Comment by Jason2866** [comment]
Thank you for testing. Another hurdle to take. There is a 50% chance it does work or not. Reason for this behaviour is identified and we are working on it to solve and provide a 99.9% solution.
In the current solution it is needed Tasmota gets OTA updated in APP slot 1. If it gets OTA updated in APP slot 2 it will fail. We don't know in which slot Tasmota firmware is. So we have to find a way to tell the bootloader which one to start OR copy the Tasmota firmware in the other OTA slot before the 2nd boot of Tasmota happens. A job that can be solved :-) Just a bit more tinkering and code...
Stay tuned.

**Comment by Jason2866** [comment]
@RavenSystem It should work now. Use the OTA convert zip AND do right after Tasmota is in you WiFi network the Autoconfig step. Without you end in a bricked device. With Autoconfig the bootloader is replaced AND the partition and which app slot to start is correctly set.

**Comment by Jason2866** [comment]
Using latest version from here https://github.com/tasmota/mgos32-to-tasmota32
and exactly following the Readme will convert Shelly devices successful.
