### ISSUE TITLE
Update provided version to latest or special (language?)

### ISSUE THREAD

**Issue by Dormin18** [phiten/mgos32-to-tasmota32#26]
Hi,

isn't it possible to update the 12.5 tasmota version after being flashed on the shelly? Trying to let me face the error message "not enough space" even with minimal package, so I assume no further version/ update of tasmota can be flashed on the device. 

Device: Shelly Plus 1 Mini
Current Version: 12.5.0
wanted version: 13.2.0

What can I do? Any ideas?

**Comment by vic42** [comment]
This question goes to the wrong repository. See https://tasmota.github.io/docs/Safeboot/ for a discussion of recent changes in Tasmota's memory layout. The layout can be changed with `Partition_Wizard.tapp`.
The "minimal" version is generally unsuitable for ESP32 based devices.

**Comment by Jason2866** [comment]
Follow the guide. You will end with latest Tasmota version using safeboot.
