### ISSUE TITLE
Shelly stock firmware v1.1.0 prevents to install Tasmota

### ISSUE THREAD

**Issue by RavenSystem** [phiten/mgos32-to-tasmota32#27]
I have several cases from users with Shelly Plus and Pro devices using firmware version 1.1.0 that avoid to install Tasmota when mgos32_to_tasmota ZIP file is loaded using web UI.

**Comment by arkn666l** [comment]
![shellypro2pm](https://github.com/phiten/mgos32-to-tasmota32/assets/132463782/6daa0661-5701-4669-bef2-6d0d7734bcad)


shelly pro 2 pm v.1 - firmware ID = 20231219-133937/1.1.0-g34b5d4f

not working OTA

**Comment by RavenSystem** [comment]
Tracked here: https://github.com/tasmota/mgos32-to-tasmota32/issues/31
