### ISSUE TITLE
Rollback to original shelly firmware

### ISSUE THREAD

**Issue by Bascht74** [phiten/mgos32-to-tasmota32#3]
Hi, I tried out moving to tasmota32 with your easy way how to it, but how can I go back?

I found that all gen2 firmware files are here: 
http://rojer.me/files/shelly/stock/

If I download the zip-file there are the following files in it:  
fs.img
bootloader.bin
manifest.json
otadata.bin
partition-table.bin
Plus1PM.bin

Is there a way to flash these files to get back to the original firmware?
I know that you repository is about going to Tasmota, but rolling back might be interesting for other people as well...

**Comment by phiten** [comment]
I never tried if it works but what you could try is flashing the Plus1PM.bin via tasmota. There is a high chance of it not working as we replace the bootloader as well as the filesystem with the OTA from Shelly. So be prepared to flash via serial.

**Comment by phiten** [comment]
@Bascht74 so I just tried it with a Pro 4PM and the Shelly .bin and it works. Ofc it's no guarantee that everything is working fine under the hood but I see no reason why it shouldn't.
