### ISSUE TITLE
Shelly Plus 2PM is working

### ISSUE THREAD

**Issue by WernerRH21** [phiten/mgos32-to-tasmota32#4]
I can confirm, that a Plus 2PM device is working.
I recognized two things: 
1. With the original firmware the ping reply was between 2-9ms and with tasmota 12.4.0 ~40-120ms. 
2. In the TasmoAdmin web interface, they are listed with version 12.4.0 single-core. Shouldn't they be listed as dual-core? I bought them on 11.0.2.2023 directly from the shelly.cloud store.

**Comment by phiten** [comment]
Both things are regarding tasmota itself. The Shelly Plus devices use the solo1 variant of tasmota to have the biggest compatibility to all different versions of PCBs/CPUs. You can always flash tasmota32.bin via OTA after the conversion. Do so at your own risk. But there is no real advantage to that as even the solo1 binary is more than quick enough.
