### ISSUE TITLE
Pro 2PM DIN Relay (PRO2PM) works

### ISSUE THREAD

**Issue by bastiedotorg** [phiten/mgos32-to-tasmota32#7]
Hi,
tried flashing my Shelly Pro 2PM DIN Relay (PRO2PM).
Base Version: 0.13
Flashing OTA worked flawlessly.
Booting to tasmota took a while and the new Shelly Cloud UI made me think it did not work. But after a few moments, the tasmota AP appeared.

Thank you for your work!

**Comment by phiten** [comment]
Thanks

**Comment by bonjour81** [comment]
Hi, it's a bit unclear to me how you flashed mongoose first to PRO2PM (as prerequisite before flashing mgos32-to-tasmota) ? I was not able to find any version of mongoose for shelly "pro" series.
How did you do ? 

I checked mongoose versions here: https://github.com/mongoose-os-apps/shelly-homekit

**Comment by bonjour81** [comment]
Ok, it seems not needed to satisfy prerequisite for PRO2PM and direct OTA can be done once shelly is updated to last firmware.
