### ISSUE TITLE
Calibration Data

### ISSUE THREAD

**Issue by dakaix** [phiten/mgos32-to-tasmota32#8]
How do I go about using the Shelly calibration data? It doesn't seem to be in a format ready for Tasmota... is there a calculation required to convert it?

**Comment by phiten** [comment]
There is no support directly for the Shelly calibration data yet. It is being worked on tho. Also different Shelly devices are using different calibration data which we are still looking into.

It is recommended to store the data somewhere safe outside of tasmota in order to use it in the future.
