### ISSUE TITLE
PlusPlugS >> confirmed working !

### ISSUE THREAD

**Issue by mebrotus** [phiten/mgos32-to-tasmota32#9]
good job !

**Comment by phiten** [comment]
Thanks

**Comment by mebrotus** [comment]
any idea on the GPIO usages ? Would it wonderfull if someone manages to find out

**Comment by phiten** [comment]
Good to hear.

Sadly I don't have this device and I'm not planning to buy one. There is a link to my Amazon wishlist in the repo which includes a Plus Plug S. If you buy it from my wishlist I will create a template for it.

**Comment by mebrotus** [comment]
Hi Phiten,

My ultimate goal is to use it with esphome, but I need the GPIO usages for that.
If I buy it fom your amazon list, will you do this ?

cheers,
________________________________
De : Philipp ***@***.***>
Envoyé : mercredi 1 mars 2023 11:22
À : phiten/mgos32-to-tasmota32 ***@***.***>
Cc : mebrotus ***@***.***>; Author ***@***.***>
Objet : Re: [phiten/mgos32-to-tasmota32] PlusPlugS >> confirmed working ! (Issue #9)


Good to hear.

Sadly I don't have this device and I'm not planning to buy one. There is a link to my Amazon wishlist in the repo which includes a Plus Plug S. If you buy it from my wishlist I will create a template for it.

**Comment by phiten** [comment]
Yes if you buy the device from my wish list I will reverse engineer it and add it to the tasmota templates. There will be a list with the GPIOs then too.

**Comment by mebrotus** [comment]
Hi Philipp,

In the meantime, I managed to get the information that I 'm happy to share with you, so I cancelled the plug order.

Pinmap is the following :
​RGB1_LEDs-GPIO25 ---> this is a string of two LEDs-first bottom left, second top left.
RGB2_LEDs-GPIO26 ---> this is a string of two LEDs-first bottom right, second top right.
SEL-GPIO19
CF1-GPIO22
CF-GPIO22
NTC-GPIO33/ADC1_CH5
Relay-GPIO4
Button-GPIO9

Rgds,
________________________________
De : Philipp ***@***.***>
Envoyé : mercredi 1 mars 2023 16:34
À : phiten/mgos32-to-tasmota32 ***@***.***>
Cc : mebrotus ***@***.***>; Author ***@***.***>
Objet : Re: [phiten/mgos32-to-tasmota32] PlusPlugS >> confirmed working ! (Issue #9)


Yes if you buy the device from my wish list I will reverse engineer it and add it to the tasmota templates. There will be a list with the GPIOs then too.
